version: 2
updates:
  # 1. Keep your GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # 2. Keep your Python dependencies (pip) up to date
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
